# Generated by Django 5.1.3 on 2024-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_profile_picture_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profile_pic',
            field=models.ImageField(default='msg_pics/blank.png', upload_to='msg_pics'),
        ),
    ]
