# Generated by Django 5.1.3 on 2024-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='profile_pic',
            field=models.ImageField(default='msg_pics/blank.png', upload_to='dp_pics'),
        ),
    ]
