# Generated by Django 5.1.3 on 2024-12-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_username_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile_pic',
        ),
    ]
